app = "nachalo-app"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "/usr/local/bin/xray run -config /etc/xray/config.json"

[[services]]
processes = ["app"]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
processes = ["app"]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    port = 3128
    handlers = []

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
