app = "nachalo-app"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = ghcr.io/mack-a/v2fly-reality:latest

[env]
  XRAY_CONFIG = "/xray.json"

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]
