app = "nachalo"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "/usr/local/bin/xray run -config /etc/xray/config.json"

# ПРОКСИ: внешний 24123 -> внутренний 3128
[[services]]
  processes = ["app"]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    processes = ["app"]
    port = 24123
    handlers = []

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150
